In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from os.path import join

import tensorflow as tf
import keras
from keras import layers, models, optimizers
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
datax = np.load(join('MNIST.npy'))
datay = np.load(join('Label.npy'))

In [3]:
datax_norm = datax/255
print('최대 : {}, 최소 : {}' .format(np.max(datax_norm), np.min(datax_norm)))

최대 : 1.0, 최소 : 0.0


In [4]:
datay_onehot = to_categorical(datay)
print(datay[0:10])
print(datay_onehot[0:10,:])
# 

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [5]:
from sklearn.model_selection import train_test_split
trnx, tstx, trny, tsty = train_test_split(datax_norm, datay_onehot, test_size=0.3, random_state=111)
print(trnx.shape)
print(tstx.shape)
print(trny.shape)
print(trnx[0].shape)
#7:3으로 나눔 

(42000, 28, 28)
(18000, 28, 28)
(42000, 10)
(28, 28)


In [6]:
input_shape = (28,28,1)
#3차원으로 바꾸기 위해
cnn_model = models.Sequential()

cnn_model.add(layers.Conv2D(12, (2,2), padding='same', input_shape=input_shape))
cnn_model.add(layers.BatchNormalization()) #배치 정규화 시키는 층 추가
cnn_model.add(layers.Activation("elu")) # elu 층 추가
cnn_model.add(layers.MaxPooling2D((2,2))) 

cnn_model.add(layers.Conv2D(24, (2,2), padding='same'))
cnn_model.add(layers.BatchNormalization())
cnn_model.add(layers.Activation("sigmoid"))
cnn_model.add(layers.Dropout(0.2))
cnn_model.add(layers.MaxPooling2D((2,2)))

cnn_model.add(layers.Flatten())

cnn_model.add(layers.Dense(units = 128, activation = "relu"))
cnn_model.add(layers.Dense(units = 10, activation =  "softmax"))

cnn_model.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [7]:
trnx_reshape = trnx.reshape(-1,28,28,1)
tstx_reshape = tstx.reshape(-1,28,28,1)
print(trnx_reshape.shape)
# 이미지인식, 이미지처리 하는데 많이 쓴다고 한다.

(42000, 28, 28, 1)


In [8]:
history = cnn_model.fit(trnx_reshape, trny, validation_data = [tstx_reshape, tsty], batch_size=2048, epochs=30)

Instructions for updating:
Use tf.cast instead.
Train on 42000 samples, validate on 18000 samples
Epoch 1/30
42000/42000 [==============================] - 41s 965us/step - loss: 2.0579 - acc: 0.3478 - val_loss: 1.6832 - val_acc: 0.6597
Epoch 2/30
42000/42000 [==============================] - 47s 1ms/step - loss: 1.3183 - acc: 0.7057 - val_loss: 1.1521 - val_acc: 0.7907
Epoch 3/30
42000/42000 [==============================] - 42s 1ms/step - loss: 0.8723 - acc: 0.8105 - val_loss: 0.8164 - val_acc: 0.8383
Epoch 4/30
42000/42000 [==============================] - 47s 1ms/step - loss: 0.6230 - acc: 0.8558 - val_loss: 0.6293 - val_acc: 0.8746
Epoch 5/30
42000/42000 [==============================] - 45s 1ms/step - loss: 0.4778 - acc: 0.8852 - val_loss: 0.5020 - val_acc: 0.8970
Epoch 6/30
42000/42000 [==============================] - 49s 1ms/step - loss: 0.3862 - acc: 0.9063 - val_loss: 0.4202 - val_acc: 0.9101
Epoch 7/30
42000/42000 [==============================] - 54s 1ms/step - loss: